name: Test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-24.04 # run on the latest image only
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Compile tests
        run: make all

      - name: Execute tests
        working-directory: ./build
        run: ./*.out
