name: Test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-24.04 # run on the latest image only
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
    
      - name: Checkout Eigen library
        uses: actions/checkout@v4
        with:
          repository: https://github.com/PX4/eigen
          path: eigen

      - name: Compile tests
        run: make all

      - name: Execute tests
        working-directory: ./build
        run: ./*.out
